### ISSUE TITLE
Better component generation for MenuItem for each ENPOINT/DATA_NAME pair

### ISSUE THREAD

**Issue by croft1** [croft1/bendigo-data-visualisation#2]
From the MenuItem's in the AppBar's Drawer, we can now define what the current dataset is and the title of the page by passing through the information the button is pertaining to.

An optimal way to go about this would be to generate the buttons by passing throuhg a map (js obj). with the TITLE and ENDPOINT pairs for cleaner execution. 

I'll save that for a rainy day (later date) or if someone wants to give it a crack. 

It's just rearranging code in Drawer.js

ALL THE BEST :100:

**Comment by bonnieetc** [comment]
Hi! If you'd still like help with this, I'll have a go at it?

**Comment by croft1** [comment]
Hi Bonnie, sure thing. Let me know if you have any questions and i'll be (reasonably) prompt, then when you're done flick over a PR.

**Comment by bonnieetc** [comment]
Great, thank you! I'm new to OS so sorry if this is obvious, but I can't seem to push a new branch. Should I create a fork and submit a PR that way instead?

**Comment by croft1** [comment]
Thats fine mate, we've all been there. Yeah you need to fork the repo, and then when you're good flick over  that PR and ill review it

**Comment by bonnieetc** [comment]
Thanks! I just submitted the PR - let me know if there are any problems/I misunderstood anything.
