### ISSUE TITLE
Dynamically change the colour of the SVGicon for Markers  when theme is changed

### ISSUE THREAD

**Issue by croft1** [croft1/bendigo-data-visualisation#6]
Within MapDataItem we currently just import the SVG icon from a local file and render that.

I was hoping there'd be a way we could get either the straight pasted code : see line 47 and change the Marker icon to be that (which means we can directly edit the FILL property of the svg) or some other lovely way of managing the colour of a Markers icon.

**Comment by RamziHossari** [comment]
You can make symbols to use for the icon as seen here.

https://developers.google.com/maps/documentation/javascript/examples/marker-symbol-custom

**Comment by croft1** [comment]
well done that is all complete, merged in 658a8b6062e64ffa112f1abf378233a75f4e39ff from #9
